Repository analogdevicesinc/hdl, pull requests merged in 2023-10, with the labels that each got.

#1130 DC2677A - LTC235x: Initial Design
  library/Makefile
  library/axi_ltc235x/Makefile
  library/axi_ltc235x/axi_ltc235x.v
  library/axi_ltc235x/axi_ltc235x_cmos.v
  library/axi_ltc235x/axi_ltc235x_hw.tcl
  library/axi_ltc235x/axi_ltc235x_lvds.v
  projects/dc2677a/Makefile
  projects/dc2677a/Readme.md
  projects/dc2677a/c5soc/Makefile
  projects/dc2677a/c5soc/system_constr.sdc
  projects/dc2677a/c5soc/system_project.tcl
  projects/dc2677a/c5soc/system_qsys.tcl
  projects/dc2677a/c5soc/system_top_cmos.v
  projects/dc2677a/c5soc/system_top_lvds.v
  projects/dc2677a/common/dc2677a_qsys.tcl
Labels: newboard

#1185 up_dac_channel: Cosmetics - fix indentation
  library/common/up_dac_channel.v
Labels: cosmetics

#1191 Update README, misspelings, and improvements
  README.md
  docs/conf.py
  docs/extensions/adi_hdl_parser.py
  docs/library/spi_engine/instruction-format.rst
  docs/library/spi_engine/tutorial.rst
  docs/sources/custom.css
Labels: doc

#1193 FMC pinout configurations for AD4630.
  projects/ad4630_fmc/common/ad4630_fmc.txt
  projects/ad4630_fmc/zed/system_constr.xdc
  projects/ad4630_fmc/zed/system_constr_4sdi.xdc
Labels: doc
