Repository analogdevicesinc/hdl, pull requests merged in 2024-03, with the labels that each got.

#1282 hdl: Zed-AD7768: Wideband fixed bug_2022_R2
  projects/ad7768evb/Makefile
  projects/ad7768evb/zed/Makefile
  projects/ad7768evb/zed/system_top.v
Labels: bug

#1192 projects/max96724/kv260: Initial commit
  projects/max96724/Makefile
  projects/max96724/Readme.md
  projects/max96724/kv260/Makefile
  projects/max96724/kv260/system_bd.tcl
  projects/max96724/kv260/system_constr.xdc
  projects/max96724/kv260/system_project.tcl
  projects/max96724/kv260/system_top.v
Labels: newcarrier

#1283 docs: Add ad7768 documentation
  docs/projects/ad7768evb/ad7768evb_fmc_hdl.svg
  docs/projects/ad7768evb/index.rst
  docs/projects/index.rst
Labels: doc
