Repository analogdevicesinc/hdl, pull requests merged in 2024-04, with the labels that each got.

#1209 ADD adaq42xx
  docs/projects/ad4630_fmc/adaq42xx_hdl_cm0_cz2_1.svg
  docs/projects/ad4630_fmc/adaq42xx_hdl_cm1_cz2_1.svg
  docs/projects/ad4630_fmc/index.rst
  docs/projects/index.rst
  projects/ad4630_fmc/common/ad4030_fmc.txt
  projects/ad4630_fmc/common/ad463x_bd.tcl
  projects/ad4630_fmc/common/adaq42xx_fmc.txt
  projects/ad4630_fmc/zed/README.md
  projects/ad4630_fmc/zed/system_constr.xdc
  projects/ad4630_fmc/zed/system_top.v
Labels: enhancement, newboard, new feature

#1291 util_do_ram: Added keep signal to the FIFO
  library/util_do_ram/util_do_ram.v
Labels: bug

#1274 docs: Add pulsar_lvds project documentation
  docs/projects/index.rst
  docs/projects/pulsar_lvds/index.rst
  docs/projects/pulsar_lvds/pulsar_lvds_block_diagram.svg
Labels: doc

#1260 axi_logic_analyzer: Improve overwrite control logic
  library/axi_logic_analyzer/axi_logic_analyzer.v
Labels: bug

#1206 Ad7606 serial/parallel interface
  library/axi_ad7606x/axi_ad7606x.v
  projects/ad7606x_fmc/Readme.md
  projects/ad7606x_fmc/common/ad7606x_bd.tcl
  projects/ad7606x_fmc/common/ad7606x_fmc.txt
  projects/ad7606x_fmc/zed/Makefile
  projects/ad7606x_fmc/zed/system_bd.tcl
  projects/ad7606x_fmc/zed/system_constr.tcl
  projects/ad7606x_fmc/zed/system_constr.xdc
  projects/ad7606x_fmc/zed/system_project.tcl
  projects/ad7606x_fmc/zed/system_top_pi.v
  projects/ad7606x_fmc/zed/system_top_si.v
Labels: new feature

#1223 docs: Add ad7606 documentation
  docs/projects/ad7606x_fmc/ad7606x_parallel_hdl.svg
  docs/projects/ad7606x_fmc/ad7606x_serial_hdl.svg
  docs/projects/ad7606x_fmc/index.rst
  docs/projects/index.rst
Labels: doc
