Repository analogdevicesinc/hdl, pull requests merged in 2024-02, with the labels that each got.

#1256 projects/adrv9026: Add reference design for ADRV9026+ZCU102
  projects/adrv9026/Makefile
  projects/adrv9026/common/adrv9026_bd.tcl
  projects/adrv9026/common/adrv9026_fmc.txt
  projects/adrv9026/zcu102/Makefile
  projects/adrv9026/zcu102/system_bd.tcl
  projects/adrv9026/zcu102/system_constr.xdc
  projects/adrv9026/zcu102/system_project.tcl
  projects/adrv9026/zcu102/system_top.v
Labels: newboard

#1264 docs: Fix mistakes in documentations
  docs/projects/ad9434_fmc/index.rst
Labels: doc

#1231 SPI Engine: fix early sdi data clear
  library/spi_engine/spi_engine_execution/spi_engine_execution.v
Labels: bug

#1207 Update cn0540 spi engine
  projects/cn0540/common/cn0540_ardz.txt
  projects/cn0540/common/cn0540_bd.tcl
  projects/cn0540/coraz7s/Makefile
  projects/cn0540/coraz7s/system_bd.tcl
  projects/cn0540/coraz7s/system_constr.xdc
  projects/cn0540/coraz7s/system_project.tcl
  projects/cn0540/coraz7s/system_top.v
Labels: enhancement

#1221 s10soc: Fixed a minor issue preventing some projects to be built.
  projects/ad9213_dual_ebz/s10soc/system_qsys.tcl
  projects/adrv9009/s10soc/system_qsys.tcl
Labels: bug

#1235 Merge adrv2crr fmcxmwbr1
  projects/adrv9009zu11eg/adrv2crr_fmcxmwbr1/system_project.tcl
  projects/adrv9009zu11eg/adrv2crr_fmcxmwbr1/system_top_fmcxmwbr1.v
  projects/adrv9009zu11eg/adrv2crr_fmcxmwbr1/system_top_xmicrowave.v
  projects/adrv9009zu11eg/adrv2crr_xmicrowave/Makefile
  projects/adrv9009zu11eg/adrv2crr_xmicrowave/system_bd.tcl
  projects/adrv9009zu11eg/adrv2crr_xmicrowave/system_constr.xdc
  projects/adrv9009zu11eg/adrv2crr_xmicrowave/system_project.tcl
Labels: enhancement

#1278 docs: Add cn0363_pmdz project documentation
  docs/index.rst
  docs/projects/cn0363/cn0363_hdl_block_diagram.svg
  docs/projects/cn0363/index.rst
Labels: doc

#1258 docs: Use doctools and add index to library and projects
  README.md
  docs/conf.py
  docs/extensions/adi_hdl_parser.py
  docs/extensions/adi_hdl_render.py
  docs/extensions/adi_hdl_static.py
  docs/extensions/adi_links.py
  docs/index.rst
  docs/library/index.rst
  docs/projects/ad469x_fmc/index.rst
  docs/projects/index.rst
  docs/requirements.txt
  docs/sources/custom.css
  docs/user_guide/docs_guidelines.rst
  docs/user_guide/git_repository.rst
  docs/user_guide/index.rst
Labels: doc
