Repository analogdevicesinc/hdl, pull requests merged in 2024-11, with the labels that each got.

#1466 docs/library: Add axi_clock_monitor IP doc & Update IP GUI
  docs/library/axi_clock_monitor/index.rst
  docs/library/index.rst
  library/axi_clock_monitor/axi_clock_monitor_ip.tcl
Labels: enhancement, doc

#1506 unit_level_tb: Added SV support
  library/common/tb/run_tb.sh
Labels: enhancement

#1505 ad9081_fmca_ebz: common: versal_transceiver: Force progdiv_clk to float
  projects/ad9081_fmca_ebz/common/versal_transceiver.tcl
Labels: bug

#1485 [Doc] New section regarding Intel projects workflow
  docs/user_guide/build_intel_boot_image.rst
  docs/user_guide/index.rst
Labels: doc

#1499 SPI Engine: execution improvements
  docs/regmap/adi_regmap_spi_engine.txt
  library/spi_engine/axi_spi_engine/axi_spi_engine.v
  library/spi_engine/spi_engine_execution/Makefile
  library/spi_engine/spi_engine_execution/spi_engine_execution.v
  library/spi_engine/spi_engine_execution/spi_engine_execution_hw.tcl
  library/spi_engine/spi_engine_execution/spi_engine_execution_ip.tcl
  library/spi_engine/spi_engine_execution/spi_engine_execution_shiftreg.v
Labels: enhancement

#1488 Add AD719x support on DE10-Nano
  docs/projects/ad719x_asdz/index.rst
  projects/ad719x_asdz/README.md
  projects/ad719x_asdz/de10nano/Makefile
  projects/ad719x_asdz/de10nano/system_constr.sdc
  projects/ad719x_asdz/de10nano/system_project.tcl
  projects/ad719x_asdz/de10nano/system_qsys.tcl
  projects/ad719x_asdz/de10nano/system_top.v
Labels: new feature, doc

#1508 docs/projects: Add adv7513 page
  docs/projects/adv7513/adv7513_bd.svg
  docs/projects/adv7513/index.rst
  docs/projects/index.rst
Labels: doc

#1510 docs/projects/dac_fmc_ebz: Add documentation
  docs/projects/dac_fmc_ebz/dac_fmc_ebz_block_diagram.svg
  docs/projects/dac_fmc_ebz/index.rst
  docs/projects/index.rst
Labels: doc

#1519 library/axi_dmac/tb: Updated unit level testbenches after framelock
  library/axi_dmac/tb/dma_read_shutdown_tb
  library/axi_dmac/tb/dma_read_tb
  library/axi_dmac/tb/dma_write_shutdown_tb
  library/axi_dmac/tb/dma_write_tb
Labels: bug

#1525 axi_dmac: Updated framelock interface pathing in Makefile
  library/axi_dmac/Makefile
Labels: bug

#1524 ad9081: common: ad9081_fmca_ebz_bd: Fix number of quads calculation
  projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl
Labels: bug

#1507 library: xilinx: common: ad_mmcm_drp: Add Versal family support
  library/xilinx/common/ad_mmcm_drp.v
Labels: new feature

#1509 unit_level_tb: Revert SV support
  library/common/tb/run_tb.sh
Labels: bug

#1460 axi_ad9361: Fixup LVDS RX_FRAME (#916)
  library/axi_ad9361/xilinx/axi_ad9361_lvds_if.v
Labels: bug

#1529 docs: Update releases page
  docs/user_guide/releases.rst
Labels: doc

#1511 Fixes for AD9164 on ZCU102
  projects/dac_fmc_ebz/common/config.tcl
  projects/dac_fmc_ebz/zcu102/system_bd.tcl
  projects/dac_fmc_ebz/zcu102/system_constr.xdc
  projects/dac_fmc_ebz/zcu102/system_top.v
Labels: bug, enhancement
