Repository analogdevicesinc/hdl, pull requests merged in 2025-05, with the labels that each got.

#1687 projects/ad7405fmc: Add READMEs
  projects/ad7405_fmc/README.md
  projects/ad7405_fmc/Readme.md
  projects/ad7405_fmc/zed/README.md
Labels: doc

#1705 projects/adv7513: Add README files
  docs/projects/adv7513/index.rst
  projects/adv7513/README.md
  projects/adv7513/Readme.md
  projects/adv7513/de10nano/README.md
Labels: doc

#1643 docs/library/jesd204/xgt_wizard: Add FPGAs Tranceivers documentation
  docs/library/jesd204/index.rst
  docs/library/jesd204/xgt_wizard/index.rst
  docs/library/xilinx/util_adxcvr/index.rst
  projects/scripts/gtwizard_generator.tcl
Labels: doc

#1686 projects/ad7768evb: Add READMEs
  projects/ad7768evb/README.md
  projects/ad7768evb/Readme.md
  projects/ad7768evb/zed/README.md
Labels: doc

#1713 projects/ad9082_fmca_ebz: Add READMEs
  projects/ad9082_fmca_ebz/README.md
  projects/ad9082_fmca_ebz/Readme.md
  projects/ad9082_fmca_ebz/vck190/README.md
  projects/ad9082_fmca_ebz/vcu118/README.md
  projects/ad9082_fmca_ebz/vpk180/README.md
  projects/ad9082_fmca_ebz/zc706/README.md
  projects/ad9082_fmca_ebz/zcu102/README.md
Labels: doc

#1700 library/common/ad_mem: Updated RAM initialization mode for Quartus IDE
  library/common/ad_mem.v
Labels: bug

#1691 docs: add project daq2
  docs/projects/daq2/daq2_evb_block_diagram.svg
  docs/projects/daq2/daq2_xilinx_block_diagram.svg
  docs/projects/daq2/index.rst
  docs/projects/index.rst
Labels: doc

#1732 ad9081_fmca_ebz: Add restructured ZCU102 diagram & update README
  docs/projects/ad9081_fmca_ebz/ad9081_204b_M8L4.svg
  docs/projects/ad9081_fmca_ebz/index.rst
  projects/ad9081_fmca_ebz/zcu102/README.md
Labels: doc

#1715 docs: ad4170_asdz: Fixed documentation
  docs/projects/ad4170_asdz/index.rst
Labels: doc

#1614 adrv9009: Add kcu105 support
  docs/projects/adrv9009/index.rst
  projects/adrv9009/common/adrv9009_bd.tcl
  projects/adrv9009/kcu105/Makefile
  projects/adrv9009/kcu105/system_bd.tcl
  projects/adrv9009/kcu105/system_constr.xdc
  projects/adrv9009/kcu105/system_project.tcl
  projects/adrv9009/kcu105/system_top.v
Labels: newcarrier

#1723 projects/ad9083_vna: Updated READMEs
  projects/ad9083_vna/README.md
  projects/ad9083_vna/Readme.md
  projects/ad9083_vna/zcu102/README.MD
Labels: doc

#1709 projects/ad7606x_fmc: Updated READMEs
  projects/ad7606x_fmc/README.md
  projects/ad7606x_fmc/Readme.md
  projects/ad7606x_fmc/zed/README.md
Labels: doc

#1737 projects/cn0585: Added README files
  projects/cn0585/README.md
  projects/cn0585/zed/README.md
Labels: doc

#1721 projects/daq2: Add README files
  projects/daq2/README.md
  projects/daq2/Readme.md
  projects/daq2/a10soc/README.md
  projects/daq2/kc705/README.md
  projects/daq2/kcu105/README.md
  projects/daq2/zc706/README.md
  projects/daq2/zcu102/README.md
Labels: doc

#1731 projects/adrv9009zu11eg: Updated README files
  projects/adrv9009zu11eg/README.md
  projects/adrv9009zu11eg/Readme.md
  projects/adrv9009zu11eg/adrv2crr_fmc/README.md
  projects/adrv9009zu11eg/adrv2crr_fmcomms8/README.md
  projects/adrv9009zu11eg/adrv2crr_fmcxmwbr1/README.md
Labels: doc

#1747 projects/ad9695_fmc: Remove old README
  projects/ad9695_fmc/Readme.md
Labels: doc

#1738 projects/cn0561: Updated README files
  projects/cn0561/README.md
  projects/cn0561/Readme.md
  projects/cn0561/coraz7s/README.md
  projects/cn0561/de10nano/README.md
  projects/cn0561/zed/README.md
Labels: doc
