Repository analogdevicesinc/hdl, pull requests merged in 2025-07, with the labels that each got.

#1800 projects/adrv9009zu11eg:Update READMEs with VADJ
  projects/adrv9009zu11eg/README.md
  projects/adrv9009zu11eg/adrv2crr_fmc/README.md
  projects/adrv9009zu11eg/adrv2crr_fmcomms8/README.md
  projects/adrv9009zu11eg/adrv2crr_fmcomms8/system_project.tcl
  projects/adrv9009zu11eg/adrv2crr_fmcxmwbr1/README.md
Labels: doc

#1796 projects/adrv9371x: Update READMEs with VADJ info
  projects/adrv9371x/README.md
  projects/adrv9371x/a10soc/README.md
  projects/adrv9371x/kcu105/README.md
  projects/adrv9371x/zc706/README.md
  projects/adrv9371x/zcu102/README.md
Labels: doc

#1810 ad485x_fmcz: Delete README.rst
  projects/ad485x_fmcz/zed/README.rst
Labels: doc

#1719 library/util_axis_fifo_asym: Updated IP parameterization and documentation
  docs/library/util_axis_fifo_asym/index.rst
  library/util_axis_fifo_asym/util_axis_fifo_asym.v
  library/util_axis_fifo_asym/util_axis_fifo_asym_ip.tcl
Labels: enhancement

#1779 cn0540: Add VADJ value in README
  projects/cn0540/README.md
  projects/cn0540/coraz7s/README.md
  projects/cn0540/de10nano/README.md
Labels: doc

#1794 ad9265_fmc: Add VADJ in README
  projects/ad9265_fmc/README.md
  projects/ad9265_fmc/zc706/README.md
  projects/ad9265_fmc/zed/README.md
Labels: doc

#1806 Update READMEs with VIO info for ad57xx_ardz
  projects/ad57xx_ardz/README.md
  projects/ad57xx_ardz/coraz7s/README.md
  projects/ad57xx_ardz/de10nano/README.md
Labels: doc

#1821 cn0577: Add VADJ value
  projects/cn0577/README.md
  projects/cn0577/zed/README.md
Labels: doc

#1822 ad9656_fmc: Add VADJ value
  projects/ad9656_fmc/README.md
  projects/ad9656_fmc/zcu102/README.md
Labels: doc

#1803 projects/ad4052_ardz: Add VIO
  projects/ad4052_ardz/README.md
  projects/ad4052_ardz/coraz7s/README.md
  projects/ad4052_ardz/de10nano/README.md
Labels: doc

#1809 projects/ad5758_sdz: Add VADJ value
  projects/ad5758_sdz/README.md
  projects/ad5758_sdz/zed/README.md
Labels: doc

#1776 Update READMEs with VADJ info for adv7511
  projects/adv7511/README.md
  projects/adv7511/zc702/README.md
  projects/adv7511/zc706/README.md
  projects/adv7511/zed/README.md
Labels: doc

#1811 Update READMEs with VADJ/VIO info for ad469x_evb
  projects/ad469x_evb/README.md
  projects/ad469x_evb/coraz7s/README.md
  projects/ad469x_evb/de10nano/README.md
  projects/ad469x_evb/zed/README.md
Labels: doc

#1828 Update READMEs with VADJ info for adrv904x project
  projects/adrv904x/README.md
  projects/adrv904x/zcu102/README.md
Labels: doc

#1842 projects/ad4170_asdz: Add VIO value
  projects/ad4170_asdz/README.md
  projects/ad4170_asdz/coraz7s/README.md
  projects/ad4170_asdz/de10nano/README.md
Labels: doc

#1863 Corundum ethernet
  docs/library/corundum/ethernet/k26/index.rst
  docs/library/corundum/ethernet/vcu118/index.rst
  library/corundum/corundum_core/corundum_core_ip.tcl
  library/corundum/ethernet/Makefile
  library/corundum/ethernet/ethernet_ip.tcl
  library/corundum/ethernet/k26/Makefile
  library/corundum/ethernet/k26/ethernet_k26.v
  library/corundum/ethernet/k26/ethernet_k26_ip.tcl
  library/corundum/ethernet/vcu118/Makefile
  library/corundum/ethernet/vcu118/ethernet_vcu118.v
  library/corundum/ethernet/vcu118/ethernet_vcu118_ip.tcl
  library/corundum/ethernet/xcvu11p/Makefile
  library/corundum/ethernet/xcvu11p/ethernet_xcvu11p.v
  library/corundum/ethernet/xcvu11p/ethernet_xcvu11p_ip.tcl
  library/scripts/adi_ip_xilinx.tcl
  projects/ad9081_fmca_ebz/vcu118/Makefile
  projects/ad9081_fmca_ebz/vcu118/system_bd.tcl
  projects/ad9081_fmca_ebz/vcu118/system_project.tcl
  projects/ad_gmsl2eth_sl/k26/Makefile
Labels: bug
